{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[INFO] 2020-11-03 13:41:09,993 __main__ <ipython-input-7-9c5e10b0874f>:36 크롤링을 시작했습니다.\n",
      "[INFO] 2020-11-03 13:41:09,993 __main__ <ipython-input-7-9c5e10b0874f>:36 크롤링을 시작했습니다.\n",
      "[INFO] 2020-11-03 13:41:09,993 __main__ <ipython-input-7-9c5e10b0874f>:36 크롤링을 시작했습니다.\n",
      "[INFO] 2020-11-03 13:41:09,993 __main__ <ipython-input-7-9c5e10b0874f>:36 크롤링을 시작했습니다.\n",
      "[INFO] 2020-11-03 13:41:09,993 __main__ <ipython-input-7-9c5e10b0874f>:36 크롤링을 시작했습니다.\n",
      "[WARNING] 2020-11-03 13:41:09,996 __main__ <ipython-input-7-9c5e10b0874f>:37 외부 사이트 링크는 크롤링하지 않습니다.\n",
      "[WARNING] 2020-11-03 13:41:09,996 __main__ <ipython-input-7-9c5e10b0874f>:37 외부 사이트 링크는 크롤링하지 않습니다.\n",
      "[WARNING] 2020-11-03 13:41:09,996 __main__ <ipython-input-7-9c5e10b0874f>:37 외부 사이트 링크는 크롤링하지 않습니다.\n",
      "[WARNING] 2020-11-03 13:41:09,996 __main__ <ipython-input-7-9c5e10b0874f>:37 외부 사이트 링크는 크롤링하지 않습니다.\n",
      "[WARNING] 2020-11-03 13:41:09,996 __main__ <ipython-input-7-9c5e10b0874f>:37 외부 사이트 링크는 크롤링하지 않습니다.\n",
      "[ERROR] 2020-11-03 13:41:09,997 __main__ <ipython-input-7-9c5e10b0874f>:38 페이지를 찾을 수 없습니다.\n",
      "[ERROR] 2020-11-03 13:41:09,997 __main__ <ipython-input-7-9c5e10b0874f>:38 페이지를 찾을 수 없습니다.\n",
      "[ERROR] 2020-11-03 13:41:09,997 __main__ <ipython-input-7-9c5e10b0874f>:38 페이지를 찾을 수 없습니다.\n",
      "[ERROR] 2020-11-03 13:41:09,997 __main__ <ipython-input-7-9c5e10b0874f>:38 페이지를 찾을 수 없습니다.\n",
      "[ERROR] 2020-11-03 13:41:09,997 __main__ <ipython-input-7-9c5e10b0874f>:38 페이지를 찾을 수 없습니다.\n",
      "[ERROR] 2020-11-03 13:41:10,000 __main__ <ipython-input-7-9c5e10b0874f>:43 요청 중에 예외가 발생했습니다: MissingSchema(\"Invalid URL '#invalid_url': No schema supplied. Perhaps you meant http://#invalid_url?\")\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-7-9c5e10b0874f>\", line 41, in logging_example\n",
      "    r = requests.get('#invalid_url', timeout=1)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\api.py\", line 76, in get\n",
      "    return request('get', url, params=params, **kwargs)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\api.py\", line 61, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\sessions.py\", line 516, in request\n",
      "    prep = self.prepare_request(req)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\sessions.py\", line 449, in prepare_request\n",
      "    p.prepare(\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\models.py\", line 314, in prepare\n",
      "    self.prepare_url(url, params)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\models.py\", line 388, in prepare_url\n",
      "    raise MissingSchema(error)\n",
      "requests.exceptions.MissingSchema: Invalid URL '#invalid_url': No schema supplied. Perhaps you meant http://#invalid_url?\n",
      "[ERROR] 2020-11-03 13:41:10,000 __main__ <ipython-input-7-9c5e10b0874f>:43 요청 중에 예외가 발생했습니다: MissingSchema(\"Invalid URL '#invalid_url': No schema supplied. Perhaps you meant http://#invalid_url?\")\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-7-9c5e10b0874f>\", line 41, in logging_example\n",
      "    r = requests.get('#invalid_url', timeout=1)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\api.py\", line 76, in get\n",
      "    return request('get', url, params=params, **kwargs)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\api.py\", line 61, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\sessions.py\", line 516, in request\n",
      "    prep = self.prepare_request(req)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\sessions.py\", line 449, in prepare_request\n",
      "    p.prepare(\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\models.py\", line 314, in prepare\n",
      "    self.prepare_url(url, params)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\models.py\", line 388, in prepare_url\n",
      "    raise MissingSchema(error)\n",
      "requests.exceptions.MissingSchema: Invalid URL '#invalid_url': No schema supplied. Perhaps you meant http://#invalid_url?\n",
      "[ERROR] 2020-11-03 13:41:10,000 __main__ <ipython-input-7-9c5e10b0874f>:43 요청 중에 예외가 발생했습니다: MissingSchema(\"Invalid URL '#invalid_url': No schema supplied. Perhaps you meant http://#invalid_url?\")\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-7-9c5e10b0874f>\", line 41, in logging_example\n",
      "    r = requests.get('#invalid_url', timeout=1)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\api.py\", line 76, in get\n",
      "    return request('get', url, params=params, **kwargs)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\api.py\", line 61, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\sessions.py\", line 516, in request\n",
      "    prep = self.prepare_request(req)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\sessions.py\", line 449, in prepare_request\n",
      "    p.prepare(\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\models.py\", line 314, in prepare\n",
      "    self.prepare_url(url, params)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\models.py\", line 388, in prepare_url\n",
      "    raise MissingSchema(error)\n",
      "requests.exceptions.MissingSchema: Invalid URL '#invalid_url': No schema supplied. Perhaps you meant http://#invalid_url?\n",
      "[ERROR] 2020-11-03 13:41:10,000 __main__ <ipython-input-7-9c5e10b0874f>:43 요청 중에 예외가 발생했습니다: MissingSchema(\"Invalid URL '#invalid_url': No schema supplied. Perhaps you meant http://#invalid_url?\")\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-7-9c5e10b0874f>\", line 41, in logging_example\n",
      "    r = requests.get('#invalid_url', timeout=1)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\api.py\", line 76, in get\n",
      "    return request('get', url, params=params, **kwargs)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\api.py\", line 61, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\sessions.py\", line 516, in request\n",
      "    prep = self.prepare_request(req)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\sessions.py\", line 449, in prepare_request\n",
      "    p.prepare(\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\models.py\", line 314, in prepare\n",
      "    self.prepare_url(url, params)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\models.py\", line 388, in prepare_url\n",
      "    raise MissingSchema(error)\n",
      "requests.exceptions.MissingSchema: Invalid URL '#invalid_url': No schema supplied. Perhaps you meant http://#invalid_url?\n",
      "[ERROR] 2020-11-03 13:41:10,000 __main__ <ipython-input-7-9c5e10b0874f>:43 요청 중에 예외가 발생했습니다: MissingSchema(\"Invalid URL '#invalid_url': No schema supplied. Perhaps you meant http://#invalid_url?\")\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-7-9c5e10b0874f>\", line 41, in logging_example\n",
      "    r = requests.get('#invalid_url', timeout=1)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\api.py\", line 76, in get\n",
      "    return request('get', url, params=params, **kwargs)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\api.py\", line 61, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\sessions.py\", line 516, in request\n",
      "    prep = self.prepare_request(req)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\sessions.py\", line 449, in prepare_request\n",
      "    p.prepare(\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\models.py\", line 314, in prepare\n",
      "    self.prepare_url(url, params)\n",
      "  File \"c:\\users\\edu\\project\\venv\\lib\\site-packages\\requests\\models.py\", line 388, in prepare_url\n",
      "    raise MissingSchema(error)\n",
      "requests.exceptions.MissingSchema: Invalid URL '#invalid_url': No schema supplied. Perhaps you meant http://#invalid_url?\n"
     ]
    }
   ],
   "source": [
    "from logging import (\n",
    "    getLogger,\n",
    "    Formatter,\n",
    "    FileHandler,\n",
    "    StreamHandler,\n",
    "    DEBUG,\n",
    "    ERROR,\n",
    ")\n",
    "import requests\n",
    "\n",
    "# 로거 : __name__에는 실행 모듈 이름 logging_sample이 들어감(file name)\n",
    "logger = getLogger(__name__)\n",
    "\n",
    "# 출력형식\n",
    "default_format = '[%(levelname)s] %(asctime)s %(name)s %(filename)s:%(lineno)d %(message)s'\n",
    "default_formatter = Formatter(default_format)\n",
    "funcname_formatter = Formatter(default_format +' (%(funcName)s)')\n",
    "\n",
    "# 로그 전용 핸들러: 콘솔 출력 전용\n",
    "log_stream_handler = StreamHandler()\n",
    "log_stream_handler.setFormatter(default_formatter)\n",
    "log_stream_handler.setLevel(DEBUG)\n",
    "\n",
    "# 로그 전용 핸들러: 파일 출력 전용\n",
    "log_file_handler = FileHandler(filename='crawler.log',encoding='utf-8')\n",
    "log_file_handler.setFormatter(funcname_formatter)\n",
    "log_file_handler.setLevel(ERROR)\n",
    "\n",
    "# 로거에 핸들러와 레벨 설정하기\n",
    "logger.setLevel(DEBUG)\n",
    "logger.addHandler(log_stream_handler)\n",
    "logger.addHandler(log_file_handler)\n",
    "\n",
    "\n",
    "def logging_example():\n",
    "    logger.info('크롤링을 시작했습니다.') # info 레벨로 메시지 출력\n",
    "    logger.warning('외부 사이트 링크는 크롤링하지 않습니다.') # warning 레벨로 메시지 출력하기\n",
    "    logger.error('페이지를 찾을 수 없습니다.') # error레벨로 메시지 출력하기\n",
    "    \n",
    "    try:\n",
    "        r = requests.get('#invalid_url', timeout=1)\n",
    "    except requests.exceptions.RequestException as e:\n",
    "        logger.exception('요청 중에 예외가 발생했습니다: %r',e)  # 예외의 스특트레이스 출력\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    logging_example()\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
